src/Entity/Questions.php
<?php

namespace App\Entity;

use App\Repository\QuestionsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionsRepository::class)
 */
class Questions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $text_question;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_multiple;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTextQuestion(): ?string
    {
        return $this->text_question;
    }

    public function setTextQuestion(string $text_question): self
    {
        $this->text_question = $text_question;

        return $this;
    }

    public function getIsMultiple(): ?bool
    {
        return $this->is_multiple;
    }

    public function setIsMultiple(bool $is_multiple): self
    {
        $this->is_multiple = $is_multiple;

        return $this;
    }
    public function __toString() {
        return $this->id;
    }
}

src/Entity/Reponses.php
<?php

namespace App\Entity;

use App\Repository\ReponsesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReponsesRepository::class)
 */
class Reponses
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $text_reponse;

    /**
     * @ORM\ManyToOne(targetEntity=Questions::class)
     */
    private $questions;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTextReponse(): ?string
    {
        return $this->text_reponse;
    }

    public function setTextReponse(string $text_reponse): self
    {
        $this->text_reponse = $text_reponse;

        return $this;
    }

    public function getQuestions(): ?Questions
    {
        return $this->questions;
    }

    public function setQuestions(?Questions $questions): self
    {
        $this->questions = $questions;

        return $this;
    }
    public function __toString() {
        return $this->id;
    }
}

src/Form/QuestionsType.php
<?php

namespace App\Form;

use App\Entity\Questions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuestionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('text_question')
            ->add('is_multiple')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Questions::class,
        ]);
    }
}

src/Controller/QuestionsController.php
<?php

namespace App\Controller;

use App\Entity\Reponses;
use App\Entity\Questions;
use App\Entity\Resultats;
use App\Form\ReponsesType;
use App\Form\QuestionsType;
use App\Repository\QuestionsRepository;
use App\Repository\ReponsesRepository;
use App\Repository\ResultatsRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/questions')]
class QuestionsController extends AbstractController
{
    #[Route('/', name: 'questions_index', methods: ['GET'])]
    public function index(QuestionsRepository $questionsRepository): Response
    {
        return $this->render('questions/index.html.twig', [
            'questions' => $questionsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'questions_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $question = new Questions();
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/new.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'questions_show', methods: ['GET'])]
    public function show(Questions $question, ReponsesRepository $reponsesRepository): Response
    {
        $reponses = $reponsesRepository->findBy(['questions' => $question->getId()]);
        return $this->render('questions/show.html.twig', [
            'question' => $question,
            'reponses' => $reponses
        ]);
    }

    #[Route('/{id}/edit', name: 'questions_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Questions $question): Response
    {
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/edit.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'questions_delete', methods: ['POST'])]
    public function delete(Request $request, Questions $question): Response
    {
        if ($this->isCsrfTokenValid('delete'.$question->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($question);
            $entityManager->flush();
        }

        return $this->redirectToRoute('questions_index');
    }

    #[Route('/show/{id}', name: 'questions_answer', methods: ['GET', 'POST'])]
    public function answer(Request $request, Questions $questions, ReponsesRepository $resultats): Response
    {
        if($request->getMethod() === 'POST'){
            $results = $request->request->get('answer');
            $entityManager = $this->getDoctrine()->getManager();
            foreach($results as $result){
                $answer = new Resultats();
                $answer->setUser($this->getUser());
                $answer->setUserIp($request->getClientIp());
                $answer->setReponse($resultats->find($result));
                $entityManager->persist($answer);
                $entityManager->flush();
            }
            $this->addFlash('success', 'Réponses ajouté avec succès');
            return $this->redirectToRoute('questions_index');
        }
    }
    
    #[Route('/results/{id}', name: 'questions_results', methods: ['GET'])]
    public function results(Questions $question,  ReponsesRepository $reponsesRepository, ResultatsRepository $resultatsRepository): Response
    {
        $reponses = $reponsesRepository->findBy(['questions' => $question->getId()]);
        $resultats = [];
        $resultsTotal = 0;

        foreach ($reponses as $key) {
            $resultats[$key->getId()] = count($resultatsRepository->findBy(['reponse' => $key->getId()]));
        }

        foreach($resultats as $keyy){
            $resultsTotal += $keyy;
        }
        
        
        return $this->render('questions/results.html.twig', [
            'question' => $question,
            'reponses' => $reponses,
            'resultats' => $resultats,
            'resultsTotal' => $resultsTotal
        ]);
    }
    
}

templates/questions/_delete_form.html.twig
<form method="post" action="{{ path('questions_delete', {'id': question.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn">Delete</button>
</form>

templates/questions/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/questions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Questions{% endblock %}

{% block body %}
    <h1>Edit Questions</h1>

    {{ include('questions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('questions_index') }}">back to list</a>

    {{ include('questions/_delete_form.html.twig') }}
{% endblock %}

templates/questions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions index{% endblock %}

{% block body %}
<main style="margin: 10%; text-align:center">
    <h1>Questions index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Question</th>
                <th>Is_multiple</th>
                <th>Answer Poll</th>
                <th>Update answer</th>
                <th>Show results</th>
                <th>Update</th>
            </tr>
        </thead>
        <tbody>
        {% for question in questions %}
            <tr>
                <td>{{ question.id }}</td>
                <td>{{ question.textQuestion }}</td>
                <td>{{ question.isMultiple ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('questions_show', {'id': question.id}) }}">Answer</a>
                </td>
                <td>
                    <a href="{{ path('reponses_index', {'id': question.id}) }}">update</a>
                </td>
                <td>
                    <a href="{{ path('questions_results', {'id': question.id}) }}">Results</a>
                </td>
                <td>
                    <a href="{{ path('questions_edit', {'id': question.id}) }}">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('questions_new') }}">Create new question</a>

    </main>
{% endblock %}

templates/questions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Questions{% endblock %}

{% block body %}
    <h1>Create new Questions</h1>

    {{ include('questions/_form.html.twig') }}

    <a href="{{ path('questions_index') }}">back to list</a>
{% endblock %}

templates/questions/results.html.twig
{% extends 'base.html.twig' %}

{% block title %} Résultats : {{ question.textQuestion }} {% endblock %}

{% block body %}
    <main style="padding: 2%;">
    <h1> Results of the question : {{ question.textQuestion }} </h1>

    <div style="margin-left: 2%; font-size: 20px">
        {% for reponse in reponses %}
            <p> {{reponse.textReponse}} = {{ resultats[reponse.id] }} vote(s)</p>
        {% endfor %}
    </div>

    <p> Total number of votes : {{ resultsTotal }} </p>

    <a href="{{ path('questions_index') }}"> <p style="margin-top: 2%; margin-left: 2%;"> back to list </p> </a>

    </main>
{% endblock %}

templates/questions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions{% endblock %}

{% block body %}
   <h1> {{ question.textQuestion }} </h1>

    <form action="{{ path('questions_answer', {'id': question.id}) }}" method="post" style="margin-left: 2%;">
        {% set input_type=question.isMultiple ? 'checkbox' : 'radio' %}

        {% for reponse in reponses %}
            <input type="{{input_type}}" name="answer[]" value="{{reponse.id}}"> {{reponse.textReponse}} <br />
        {% endfor %}

        <button style="margin-top: 1%;"> Envoyer </button>
    </form>

    <a href="{{ path('questions_index') }}">back to list</a>

    <a href="{{ path('questions_edit', {'id': question.id}) }}">edit</a>

    {{ include('questions/_delete_form.html.twig') }}
{% endblock %}